"""create projeto table

Revision ID: 51662797b8af
Revises: 
Create Date: 2025-07-04 16:22:53.297869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51662797b8af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('id_analise', sa.Integer(), nullable=False),
    sa.Column('descricao_tecnica', sa.Text(), nullable=True),
    sa.Column('data_inicio_projeto', sa.Date(), nullable=True),
    sa.Column('data_final_projeto', sa.Date(), nullable=True),
    sa.Column('arquiteto_responsavel', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id_projeto')
    )
    op.create_index(op.f('ix_projeto_id_projeto'), 'projeto', ['id_projeto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projeto_id_projeto'), table_name='projeto')
    op.drop_table('projeto')
    # ### end Alembic commands ###
